Micraft_Solutions/Controllers/Order_CheckController.cs
using Micraft_Solutions.Data_Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Micraft_Solutions.Controllers
{
    public class Order_CheckController : Controller
    {
        // GET: Order_Check
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Partial_View(int id)
        {
            t_order model;
            using (Db_MicraftEntities _MicraftEntities = new Db_MicraftEntities())
            {
                var getdata = new m_Product();
                getdata = _MicraftEntities.m_Product.Where(x => x.Product_Id == id).FirstOrDefault();
                TempData["Image_path"] = getdata.Product_Image;
                if (getdata != null)
                {
                    model = new t_order()
                    {
                        order_rate = Convert.ToDecimal(getdata.Product_Rate),
                        attr1=getdata.Product_Name,
                     


                    };
                    return PartialView("Index", model);
                }
             

            }
            return View();
        }
        public ActionResult Save(t_order model)
        {
            using(Db_MicraftEntities _context= new Db_MicraftEntities())
            {
                _context.Entry(model).State = System.Data.Entity.EntityState.Added;
                _context.SaveChanges();


            }
            TempData["message"] = "Your Order Place Successfully....!";
          return  RedirectToAction("Main_View", "Product_Selection");
        }
    }
}

Micraft_Solutions/Views/Order_Check/Index.cshtml
@{
    /**/

    /**/

    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @if (TempData["message"] != null)
    {
        <script type="text/javascript">
<a href="~/Views/Product/Index.cshtml">~/Views/Product/Index.cshtml</a>
                        var message = '@TempData["message"]';
                        Swal.fire("Good job!", message, "success");

        </script>
    }
    @if (TempData["Error"] != null)
    {
        <script type="text/javascript">
                        var message = '@TempData["Error"]';
                        Swal.fire("Try Again!", message, "error");
        </script>
    }
    @if (TempData["Delete"] != null)
    {
        <script type="text/javascript">

                        var message = '@TempData["Delete"]';
                        Swal.fire("Good job!", message, "warning");

        </script>
    }
</head>
<html lang="en">

<body>
    <div class="content-wrapper">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container-fluid">
                    <div class="row justify-content-center">
                        <div class="col-lg-12">
                            <div class="cord-body mt-1">

                                <!-- Nav tabs -->
                                <!-- Tab panes -->
                                <div class="tab-content">
                                    <div id="Insert" class="container-fluid tab-pane active">
                                        <div class="card-header bg-dark">
                                            <h7 class="font-weight-bolder text-center    text-white">
                                                Product
                                            </h7>


                                        </div>
                                        <div class="card-body card shadow-lg border-0 rounded-lg">
                                            @Html.Partial("~/Views/Order_Check/Partial_View.cshtml")
                                           

                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>
</body>

</html>
@section scripts{

    @Scripts.Render("~/bundles/jqueryval")
}

Micraft_Solutions/Views/Order_Check/Partial_View.cshtml
@model Micraft_Solutions.Data_Context.t_order
    @{ 
        Layout = null;
    }
<html lang="en">
<head>

    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script type="text/javascript">

        $(document).ready(function(){

            $("#id_order_qty").val(0.00)
        

            getDate()
          
        })



        function getDate() {
            var today = new Date();

            document.getElementById("Enquri_date").value = today.getFullYear() + '-' + ('0' + (today.getMonth() + 1)).slice(-2) + '-' + ('0' + today.getDate()).slice(-2);
        }

        function Total_Amount() {

            var get_rate = $("#id_order_rate").val();
            var qty = $("#id_order_qty").val();
            var Amount;
            if (qty != null) {
                Amount = parseFloat(get_rate) * parseFloat(qty)
                $("#id_order_amount").val(Amount)
            }
         
        }
    </script>

</head>
<body class="bg-primary">


    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @using (Html.BeginForm("Save", "Order_Check", FormMethod.Post))
    {
        <div class="form-row ">
            <div class="col-md-3">
                <div class="form-group ">
                    <label class="small mb-1 ">Order Date  <small style="color:red">*</small></label>

                    @Html.HiddenFor(m => m.Order_id)
                    @Html.TextBoxFor(m => m.order_date, new { @class = "form-control ", autofocus = "autofocus", tabindex = "2", type = "Date", id = "Enquri_date" })
                    @Html.ValidationMessageFor(m => m.order_date, "", new { @class = "text-danger  " })
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group ">
                    <label class="small mb-1 ">Customer Name <small style="color:red">*</small></label>
                    @Html.TextBoxFor(m => m.customer_name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.customer_name, "", new { @class = "text-danger  " })
                </div>
            </div>

            <div class="col-md-3">
                <div class="form-group ">
                    <label class="small mb-1 ">Address  <small style="color:red">*</small></label>
                    @Html.TextBoxFor(m => m.customer_address, new { @class = "form-control class_total_qty " })
                    @Html.ValidationMessageFor(m => m.customer_address, "", new { @class = "text-danger  " })

                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group ">
                    <label class="small mb-1 ">Contact  <small style="color:red">*</small></label>
                    @Html.TextBoxFor(m => m.customer_contact, new { @class = "form-control class_total_amount " })
                    @Html.ValidationMessageFor(m => m.customer_contact, "", new { @class = "text-danger  " })
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group ">
                    <label class="small mb-1 ">Product Name  <small style="color:red">*</small></label>
                    @Html.TextBoxFor(m => m.attr1, new { @class = "form-control class_total_amount ", autofocus = "autofocus", tabindex = "3", ReadOnly = "ReadOnly" })
                    @Html.ValidationMessageFor(m => m.order_qty, "", new { @class = "text-danger  " })
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group ">
                    <label class="small mb-1 ">Rate  <small style="color:red">*</small></label>
                    @Html.TextBoxFor(m => m.order_rate, new { @class = "form-control class_total_amount ", autofocus = "autofocus", tabindex = "3", id = "id_order_rate", ReadOnly = "ReadOnly" })
                    @Html.ValidationMessageFor(m => m.order_rate, "", new { @class = "text-danger  " })
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group ">
                    <label class="small mb-1 ">Qty  <small style="color:red">*</small></label>
                    @Html.TextBoxFor(m => m.order_qty, new { @class = "form-control class_total_amount ", autofocus = "autofocus", tabindex = "3", id = "id_order_qty", Onchange = "Total_Amount()", Onblur = "Total_Amount()" })
                    @Html.ValidationMessageFor(m => m.order_qty, "", new { @class = "text-danger  " })
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group ">
                    <label class="small mb-1 ">Total Amount  <small style="color:red">*</small></label>
                    @Html.TextBoxFor(m => m.order_amount, new { @class = "form-control class_total_amount ", autofocus = "autofocus", tabindex = "3", id = "id_order_amount", ReadOnly = "ReadOnly" })
                    @Html.ValidationMessageFor(m => m.order_amount, "", new { @class = "text-danger  " })
                </div>
            </div>
            @*<div class="col-md-3">
                    <div class="form-group ">

                        <img src="@Url.Content('@TempData["Image_path"]')" width="75" ,height="75" />
                    </div>
                </div>*@

        </div>
        <button type="submit" class="btn btn-dark">Place Order</button>
    }


</body>

</html>