Micraft_Solutions/Controllers/ActionTakenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Micraft_Solutions.Data_Context;
namespace Micraft_Solutions.Controllers
{
    public class ActionTakenController : Controller
    {
        // GET: ActionTaken
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Partial_View(int id)
        {
            t_order model;
            model = new t_order()
            {
                Order_id=id
            };
          
            return View(model);  
        }
        public ActionResult Action_Taken(t_order model)
        {
            var Action = model.attr3;
            using(Db_MicraftEntities _context = new Db_MicraftEntities())
            {
                _context.t_order.Attach(model);
                _context.Entry(model).Property(x => x.attr3).IsModified = true;
                _context.SaveChanges();
            }

            return RedirectToAction("Main_View", "Order_Report");
        }
    }
}

Micraft_Solutions/Views/ActionTaken/Index.cshtml
@{

    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @if (TempData["message"] != null)
    {
        <script type="text/javascript">

                        var message = '@TempData["message"]';
                        Swal.fire("Thank You!", message, "success");

        </script>
    }
    @if (TempData["Error"] != null)
    {
        <script type="text/javascript">
                        var message = '@TempData["Error"]';
                        Swal.fire("Try Again!", message, "error");
        </script>
    }
    @if (TempData["Delete"] != null)
    {
        <script type="text/javascript">

                        var message = '@TempData["Delete"]';
                        Swal.fire("Good job!", message, "warning");

        </script>
    }
</head>
<html lang="en">

<body>
    <div class="content-wrapper">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container-fluid">
                    <div class="row justify-content-center">
                        <div class="col-lg-12">
                            <div class="cord-body mt-1">

                                <!-- Nav tabs -->

                                <div class="card-header bg-dark">
                                    <h7 class="font-weight-bolder text-center    text-white">
                                        Order Report
                                    </h7>

                                </div>
                                <div class="card-body card shadow-lg border-0 rounded-lg">

                     @Html.Partial("~/Views/ActionTaken/Partial_View.cshtml");
                                </div>
                                <!-- Tab panes -->

                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>
</body>

</html>
@section scripts{

    @Scripts.Render("~/bundles/jqueryval")
}

Micraft_Solutions/Views/ActionTaken/Partial_View.cshtml
@model Micraft_Solutions.Data_Context.t_order
    @{Layout = null;}
@using (Html.BeginForm("Action_Taken", "ActionTaken", FormMethod.Post))
{
    @Html.HiddenFor(m=>m.Order_id)
    <lable>Action</lable>
    @Html.DropDownListFor(m=>m.attr3,new List<SelectListItem>
{
    new SelectListItem{Text="--Select Action Taken--",Value="0"},
    new SelectListItem{Text="Order In Progress",Value="Order In Progress"},
    new SelectListItem{Text="Order In Deliver",Value="Order Deliver"},
    new SelectListItem{Text="Order In Rejected",Value="Order Rejected"}


},new { @class="form-control"})

   <button type="submit" class="btn btn-danger">Action</button>
}